In [1]:
import pandas as pd

In [2]:
X_train = pd.read_csv('../data/raw/h1n1_train_features.csv')

In [4]:
X_train.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [12]:
X_train.shape

(26707, 36)

In [14]:
def percent_nans(df):
    x = ['column_name','n_nans', 'percentage_nans']
    missing_data = pd.DataFrame(columns=x)
    columns = df.columns
    for col in columns:
        acolumn_name = col
        amissing_data = df[col].isnull().sum()
        amissing_in_percentage = (df[col].isnull().sum()/df[col].shape[0])*100
        missing_data.loc[len(missing_data)] = [acolumn_name, amissing_data, amissing_in_percentage]
    return missing_data

percent_nans(X_train)

                    column_name n_nans  percentage_nans
0                 respondent_id      0         0.000000
1                  h1n1_concern     92         0.344479
2                h1n1_knowledge    116         0.434343
3     behavioral_antiviral_meds     71         0.265848
4          behavioral_avoidance    208         0.778822
5          behavioral_face_mask     19         0.071142
6         behavioral_wash_hands     42         0.157262
7   behavioral_large_gatherings     87         0.325757
8       behavioral_outside_home     82         0.307036
9         behavioral_touch_face    128         0.479275
10             doctor_recc_h1n1   2160         8.087767
11         doctor_recc_seasonal   2160         8.087767
12        chronic_med_condition    971         3.635751
13         child_under_6_months    820         3.070356
14                health_worker    804         3.010447
15             health_insurance  12274        45.957989
16  opinion_h1n1_vacc_effective    391         1.464036
17            opinion_h1n1_risk    388         1.452803
18  opinion_h1n1_sick_from_vacc    395         1.479013
19  opinion_seas_vacc_effective    462         1.729884
20            opinion_seas_risk    514         1.924589
21  opinion_seas_sick_from_vacc    537         2.010709
22                    age_group      0         0.000000
23                    education   1407         5.268282
24                         race      0         0.000000
25                          sex      0         0.000000
26               income_poverty   4423        16.561201
27               marital_status   1408         5.272026
28                  rent_or_own   2042         7.645936
29            employment_status   1463         5.477965
30               hhs_geo_region      0         0.000000
31                   census_msa      0         0.000000
32             household_adults    249         0.932340
33           household_children    249         0.932340
34          employment_industry  13330        49.912008
35        employment_occupation  13470        50.436215

In [16]:
X_train.health_insurance.value_counts(dropna=False)

1.0    12697
NaN    12274
0.0     1736
Name: health_insurance, dtype: int64

In [21]:
X_train.census_msa.value_counts(dropna=False)

MSA, Not Principle  City    11645
MSA, Principle City          7864
Non-MSA                      7198
Name: census_msa, dtype: int64

In [23]:
X_train = X_train.drop(columns=['employment_industry',
                                'employment_occupation'])

In [22]:
X_train.income_poverty.value_counts(dropna=False)

<= $75,000, Above Poverty    12777
> $75,000                     6810
NaN                           4423
Below Poverty                 2697
Name: income_poverty, dtype: int64